#!/bin/bash

#SBATCH --time=24:00:00
#SBATCH --partition=shas
#SBATCH --ntasks=4862
#SBATCH --job-name=size5_job1
#SBATCH --output=/scratch/summit/tato5939/output/size5_job1.%j.out

module purge
module load python/3.6.5
module load loadbalance

source /curc/sw/anaconda3/latest
conda activate tpt

mpirun lb size5_job1_cmd_file

echo "done"
