#!/bin/bash

#SBATCH --time=06:00:00
#SBATCH --partition=shas
#SBATCH --ntasks=442
#SBATCH --job-name=size3_job1
#SBATCH --output=output/size3_job1.%j.out

module purge
module load python/3.6.5
module load loadbalance

source /curc/sw/anaconda3/latest
conda activate tpt

mpirun lb size3_job1_cmd_file

echo "done"
