#!/bin/bash

#SBATCH --time=24:00:00
#SBATCH --partition=shas
#SBATCH --ntasks=1768
#SBATCH --job-name=size6_job3
#SBATCH --output=/scratch/summit/tato5939/output/size6_job3.%j.out

module purge
module load python/3.6.5
module load loadbalance

source /curc/sw/anaconda3/latest
conda activate tpt

mpirun lb size6_job3_cmd_file

echo "done"
