#!/bin/bash

#SBATCH --time=24:00:00
#SBATCH --partition=shas
#SBATCH --ntasks=5304
#SBATCH --qos=long
#SBATCH --job-name=size7_job1
#SBATCH --output=output/size7_job1.%j.out

module purge
module load python/3.6.5
module load loadbalance

source /curc/sw/anaconda3/latest
conda activate tpt

mpirun lb size7_job1_cmd_file

echo "done"
