#!/bin/bash

#SBATCH --time=06:00:00
#SBATCH --partition=shas-testing
#SBATCH --ntasks=24
#SBATCH --job-name=test_job_size5
#SBATCH --output=output/test_job_size5.%j.out

module purge
module load python/3.6.5
module load loadbalance

source /curc/sw/anaconda3/latest
conda activate tpt

mpirun lb test_job_size5_cmd_file

echo "done"
