#!/bin/bash

#SBATCH --time=06:00:00
#SBATCH --partition=shas
#SBATCH --ntasks=1
#SBATCH --job-name=size5_india_job1
#SBATCH --output=/scratch/summit/tato5939/test-job-3/output/size5_india_job1.%j.out

module purge
module load python/3.6.5
module load loadbalance

source /curc/sw/anaconda3/latest
conda activate tpt

mpirun lb size5_india_job1_cmd_file

echo "done"
