#!/bin/bash

#SBATCH --time=00:30:00
#SBATCH --partition=shas-testing
#SBATCH --ntasks=1
#SBATCH --job-name=size7_job1_test
#SBATCH --output=/projects/tato5939/test-job-3/output/size7_job1_test.%j.out

module purge
module load python/3.6.5
module load loadbalance

source /curc/sw/anaconda3/latest
conda activate tpt

mpirun lb size7_job1_cmd_file_test

echo "done"
