#!/bin/bash

#SBATCH --nodes=1
#SBATCH --time=00:05:00
#SBATCH --partition=shas-testing
#SBATCH --ntasks=1
#SBATCH --job-name=tpt-test-job
#SBATCH --output=tpt-test-job.%j.out

module purge
module load python/3.6.5

python test.py

echo "done"
